/**
 * Full Atlantico translations for groupDetails + eventDetails.
 *
 * Source:
 * - Generated by scripts/translate-all.mjs into data/atlantico-translations-full.json
 *
 * Shape:
 * {
 *   [code]: {
 *     [lang]: {
 *       groupDetails: {
 *         name, desc, willDo, faq, canDesc, childAge, infantAge
 *       },
 *       eventOptions: Array<{
 *         eventId: string
 *         name: string
 *         desc: string
 *       }>
 *     }
 *   }
 * }
 */

import type { Locale } from '@/i18n/request'
import fullTranslations from '@/data/atlantico-translations-full.json'

type AtlanticoLang = 'fr' | 'es' | 'de' | 'ru' | 'pl' | 'it'

type GroupDetailsFields = {
  name?: string
  desc?: string
  willDo?: string
  faq?: string
  canDesc?: string
  childAge?: string
  infantAge?: string
}

type EventOptionFields = {
  eventId: string
  name?: string
  desc?: string
}

type CodeTranslations = {
  groupDetails?: GroupDetailsFields
  eventOptions?: EventOptionFields[]
}

type FullTranslationMap = Record<string, Record<AtlanticoLang, CodeTranslations>>

// The JSON file is generated by translate-all and may be partially filled for some codes/langs.
// We trust its structure at runtime and cast via unknown to satisfy TypeScript.
const translations = fullTranslations as unknown as FullTranslationMap

function mapLocaleToAtlanticoLang(locale: Locale): AtlanticoLang | null {
  const lower = locale.toLowerCase() as string
  switch (lower) {
    case 'fr':
    case 'fr-fr':
      return 'fr'
    case 'es':
    case 'es-es':
      return 'es'
    case 'de':
    case 'de-de':
      return 'de'
    case 'ru':
    case 'ru-ru':
      return 'ru'
    case 'pl':
    case 'pl-pl':
      return 'pl'
    case 'it':
    case 'it-it':
      return 'it'
    default:
      return null
  }
}

export type AtlanticoField =
  | 'name'
  | 'desc'
  | 'willDo'
  | 'faq'
  | 'cancellationPolicy'
  | 'childAge'
  | 'infantAge'

interface TranslationOptions {
  /** When provided, read from eventOptions instead of groupDetails */
  eventId?: string
  /** English (or original) fallback text */
  fallback?: string
}

/**
 * Get a translated Atlantico field for a given tour code / locale.
 *
 * - If locale is "en", always returns the fallback as-is.
 * - If the translation map has no entry for the code/lang/field, returns fallback.
 * - For event options, you must pass eventId in options.
 */
export function getAtlanticoTranslation(
  code: string | null | undefined,
  locale: Locale,
  field: AtlanticoField,
  options: TranslationOptions = {}
): string {
  const fallback = options.fallback ?? ''
  if (!code) return fallback

  // English: we always show the original ENG text
  if (locale === 'en') return fallback

  const lang = mapLocaleToAtlanticoLang(locale)
  if (!lang) return fallback

  const codeStr = String(code).trim()
  if (!codeStr) return fallback

  const perCode = translations[codeStr]
  if (!perCode) return fallback

  const perLang = perCode[lang]
  if (!perLang) return fallback

  // Event options path
  if (options.eventId) {
    const opts = perLang.eventOptions ?? []
    const match = opts.find((o) => String(o.eventId) === String(options.eventId))
    if (!match) return fallback
    if (field === 'name') return match.name || fallback
    if (field === 'desc') return match.desc || fallback
    // Other fields don't exist for options – fall back.
    return fallback
  }

  // Group details path
  const gd = perLang.groupDetails
  if (!gd) return fallback

  switch (field) {
    case 'name':
      return gd.name || fallback
    case 'desc':
      return gd.desc || fallback
    case 'willDo':
      return gd.willDo || fallback
    case 'faq':
      return gd.faq || fallback
    case 'cancellationPolicy':
      // Stored as canDesc in the JSON
      return gd.canDesc || fallback
    case 'childAge':
      return gd.childAge || fallback
    case 'infantAge':
      return gd.infantAge || fallback
    default:
      return fallback
  }
}

