/**
 * Auto-generated by scripts/download-group-details-images.mjs
 * Maps group code -> local image paths for group details galleries
 */
export const GROUP_DETAILS_IMAGES: Record<string, string[]> = {
  "508": [
    "/images/pictures/tours-vip/508/group-details-2.jpg",
    "/images/pictures/tours-vip/508/group-details-3.jpg",
    "/images/pictures/tours-vip/508/group-details-4.jpg",
    "/images/pictures/tours-vip/508/group-details-5.jpg"
  ],
  "303": [
    "/images/pictures/tours-vip/303/group-details-2.jpg",
    "/images/pictures/tours-vip/303/group-details-3.jpg",
    "/images/pictures/tours-vip/303/group-details-4.jpg",
    "/images/pictures/tours-vip/303/group-details-5.jpg"
  ],
  "403": [
    "/images/pictures/tours-vip/403/group-details-2.jpg",
    "/images/pictures/tours-vip/403/group-details-3.jpg",
    "/images/pictures/tours-vip/403/group-details-4.jpg",
    "/images/pictures/tours-vip/403/group-details-5.jpg",
    "/images/pictures/tours-vip/403/group-details-6.jpg"
  ],
  "476": ["/images/pictures/tours-vip/476/group-details-1.jpg"],
  "492": ["/images/pictures/tours-vip/492/group-details-1.jpg"],
  "514": ["/images/pictures/tours-vip/514/group-details-1.jpg"],
  "551": ["/images/pictures/tours-vip/551/group-details-1.jpg"],
  "417": [
    "/images/pictures/tours-vip/417/group-details-1.png",
    "/images/pictures/tours-vip/417/group-details-2.png",
    "/images/pictures/tours-vip/417/group-details-3.png",
    "/images/pictures/tours-vip/417/group-details-4.png",
    "/images/pictures/tours-vip/417/group-details-5.png"
  ]
}
