/**
 * Auto-generated by scripts/scan-group-details-folders.mjs
 * Maps group code -> local image paths for group details hero galleries
 * Add images in public/images/pictures/tours-vip/{code}/ and run: pnpm scan:group-images
 */
export const GROUP_DETAILS_IMAGES: Record<string, string[]> = {
  "215": [
    "/images/pictures/tours-vip/215/group-details-1.png",
    "/images/pictures/tours-vip/215/group-details-2.png",
    "/images/pictures/tours-vip/215/group-details-3.png",
    "/images/pictures/tours-vip/215/group-details-4.png",
    "/images/pictures/tours-vip/215/group-details-5.png"
  ],
  "303": [
    "/images/pictures/tours-vip/303/group-details-2.jpg",
    "/images/pictures/tours-vip/303/group-details-3.jpg",
    "/images/pictures/tours-vip/303/group-details-4.jpg",
    "/images/pictures/tours-vip/303/group-details-5.jpg"
  ],
  "403": [
    "/images/pictures/tours-vip/403/group-details-2.jpg",
    "/images/pictures/tours-vip/403/group-details-3.jpg",
    "/images/pictures/tours-vip/403/group-details-4.jpg",
    "/images/pictures/tours-vip/403/group-details-5.jpg",
    "/images/pictures/tours-vip/403/group-details-6.jpg"
  ],
  "416": [
    "/images/pictures/tours-vip/416/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20135215.png",
    "/images/pictures/tours-vip/416/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20135308.png",
    "/images/pictures/tours-vip/416/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20135336.png",
    "/images/pictures/tours-vip/416/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20135400.png",
    "/images/pictures/tours-vip/416/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20135423.png"
  ],
  "417": [
    "/images/pictures/tours-vip/417/group-details-1.png",
    "/images/pictures/tours-vip/417/group-details-2.png",
    "/images/pictures/tours-vip/417/group-details-3.png",
    "/images/pictures/tours-vip/417/group-details-4.png",
    "/images/pictures/tours-vip/417/group-details-5.png"
  ],
  "427": [
    "/images/pictures/tours-vip/427/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20140155.png",
    "/images/pictures/tours-vip/427/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20140235.png",
    "/images/pictures/tours-vip/427/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20140258.png",
    "/images/pictures/tours-vip/427/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20140319.png"
  ],
  "432": [
    "/images/pictures/tours-vip/432/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20140409.png",
    "/images/pictures/tours-vip/432/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20140516.png",
    "/images/pictures/tours-vip/432/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20140540.png",
    "/images/pictures/tours-vip/432/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20140609.png",
    "/images/pictures/tours-vip/432/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20140633.png"
  ],
  "435": [
    "/images/pictures/tours-vip/435/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20142011.png",
    "/images/pictures/tours-vip/435/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20142048.png",
    "/images/pictures/tours-vip/435/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20142113.png",
    "/images/pictures/tours-vip/435/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20142135.png",
    "/images/pictures/tours-vip/435/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20142159.png"
  ],
  "436": [
    "/images/pictures/tours-vip/436/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20150015.png",
    "/images/pictures/tours-vip/436/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20150052.png",
    "/images/pictures/tours-vip/436/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20150114.png",
    "/images/pictures/tours-vip/436/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20150140.png",
    "/images/pictures/tours-vip/436/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20150200.png"
  ],
  "438": [
    "/images/pictures/tours-vip/438/group-details/d.png",
    "/images/pictures/tours-vip/438/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20124837.png",
    "/images/pictures/tours-vip/438/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20124858.png",
    "/images/pictures/tours-vip/438/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20124923.png",
    "/images/pictures/tours-vip/438/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20124945.png"
  ],
  "439": [
    "/images/pictures/tours-vip/439/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144607.png",
    "/images/pictures/tours-vip/439/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144648.png",
    "/images/pictures/tours-vip/439/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144711.png",
    "/images/pictures/tours-vip/439/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144734.png",
    "/images/pictures/tours-vip/439/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144805.png"
  ],
  "440": [
    "/images/pictures/tours-vip/440/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145404.png",
    "/images/pictures/tours-vip/440/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145451.png",
    "/images/pictures/tours-vip/440/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145514.png",
    "/images/pictures/tours-vip/440/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145536.png",
    "/images/pictures/tours-vip/440/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145557.png"
  ],
  "452": [
    "/images/pictures/tours-vip/452/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20153353.png",
    "/images/pictures/tours-vip/452/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20153436.png",
    "/images/pictures/tours-vip/452/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20153500.png",
    "/images/pictures/tours-vip/452/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20153519.png",
    "/images/pictures/tours-vip/452/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20153542.png"
  ],
  "453": [
    "/images/pictures/tours-vip/453/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20135526.png",
    "/images/pictures/tours-vip/453/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20135605.png",
    "/images/pictures/tours-vip/453/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20135633.png",
    "/images/pictures/tours-vip/453/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20135659.png",
    "/images/pictures/tours-vip/453/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20135734.png"
  ],
  "456": [
    "/images/pictures/tours-vip/456/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145719.png",
    "/images/pictures/tours-vip/456/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145755.png",
    "/images/pictures/tours-vip/456/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145816.png",
    "/images/pictures/tours-vip/456/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145840.png",
    "/images/pictures/tours-vip/456/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145859.png"
  ],
  "457": [
    "/images/pictures/tours-vip/457/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20142548.png",
    "/images/pictures/tours-vip/457/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20142628.png",
    "/images/pictures/tours-vip/457/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20142648.png",
    "/images/pictures/tours-vip/457/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20142708.png",
    "/images/pictures/tours-vip/457/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20142729.png"
  ],
  "459": [
    "/images/pictures/tours-vip/459/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144903.png",
    "/images/pictures/tours-vip/459/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144942.png",
    "/images/pictures/tours-vip/459/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145005.png",
    "/images/pictures/tours-vip/459/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145024.png",
    "/images/pictures/tours-vip/459/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145046.png"
  ],
  "460": [
    "/images/pictures/tours-vip/460/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20150250.png",
    "/images/pictures/tours-vip/460/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20150329.png",
    "/images/pictures/tours-vip/460/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20150422.png",
    "/images/pictures/tours-vip/460/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20150444.png",
    "/images/pictures/tours-vip/460/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20150514.png"
  ],
  "463": [
    "/images/pictures/tours-vip/463/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20153636.png",
    "/images/pictures/tours-vip/463/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20153715.png",
    "/images/pictures/tours-vip/463/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20153737.png",
    "/images/pictures/tours-vip/463/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20153800.png",
    "/images/pictures/tours-vip/463/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20153821.png"
  ],
  "464": [
    "/images/pictures/tours-vip/464/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20153915.png",
    "/images/pictures/tours-vip/464/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20154110.png",
    "/images/pictures/tours-vip/464/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20154138.png",
    "/images/pictures/tours-vip/464/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20154203.png"
  ],
  "469": [
    "/images/pictures/tours-vip/469/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20154619.png",
    "/images/pictures/tours-vip/469/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20154700.png",
    "/images/pictures/tours-vip/469/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20154722.png",
    "/images/pictures/tours-vip/469/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20154745.png",
    "/images/pictures/tours-vip/469/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20154807.png"
  ],
  "472": [
    "/images/pictures/tours-vip/472/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141417.png",
    "/images/pictures/tours-vip/472/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141458.png",
    "/images/pictures/tours-vip/472/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141523.png",
    "/images/pictures/tours-vip/472/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141543.png",
    "/images/pictures/tours-vip/472/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141607.png"
  ],
  "475": [
    "/images/pictures/tours-vip/475/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20154324.png",
    "/images/pictures/tours-vip/475/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20154406.png",
    "/images/pictures/tours-vip/475/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20154428.png",
    "/images/pictures/tours-vip/475/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20154500.png",
    "/images/pictures/tours-vip/475/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20154525.png"
  ],
  "477": [
    "/images/pictures/tours-vip/477/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20124100.png",
    "/images/pictures/tours-vip/477/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20124228.png",
    "/images/pictures/tours-vip/477/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20124253.png",
    "/images/pictures/tours-vip/477/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20124324.png",
    "/images/pictures/tours-vip/477/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20124349.png"
  ],
  "478": [
    "/images/pictures/tours-vip/478/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20135822.png",
    "/images/pictures/tours-vip/478/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20135859.png",
    "/images/pictures/tours-vip/478/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20135920.png",
    "/images/pictures/tours-vip/478/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20135946.png",
    "/images/pictures/tours-vip/478/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20140008.png"
  ],
  "479": [
    "/images/pictures/tours-vip/479/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20155341.png",
    "/images/pictures/tours-vip/479/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20155434.png",
    "/images/pictures/tours-vip/479/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20155457.png",
    "/images/pictures/tours-vip/479/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20155524.png",
    "/images/pictures/tours-vip/479/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20155544.png"
  ],
  "480": [
    "/images/pictures/tours-vip/480/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20154921.png",
    "/images/pictures/tours-vip/480/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20155014.png",
    "/images/pictures/tours-vip/480/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20155037.png",
    "/images/pictures/tours-vip/480/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20155100.png",
    "/images/pictures/tours-vip/480/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20155121.png"
  ],
  "481": [
    "/images/pictures/tours-vip/481/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144033.png",
    "/images/pictures/tours-vip/481/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144105.png",
    "/images/pictures/tours-vip/481/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144125.png",
    "/images/pictures/tours-vip/481/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144148.png",
    "/images/pictures/tours-vip/481/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144215.png"
  ],
  "492": [
    "/images/pictures/tours-vip/492/group-details-1.jpg.png"
  ],
  "505": [
    "/images/pictures/tours-vip/505/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20142247.png",
    "/images/pictures/tours-vip/505/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20142343.png",
    "/images/pictures/tours-vip/505/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20142407.png",
    "/images/pictures/tours-vip/505/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20142431.png",
    "/images/pictures/tours-vip/505/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20142455.png"
  ],
  "506": [
    "/images/pictures/tours-vip/506/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20152100.png",
    "/images/pictures/tours-vip/506/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20152141.png",
    "/images/pictures/tours-vip/506/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20152203.png",
    "/images/pictures/tours-vip/506/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20152227.png",
    "/images/pictures/tours-vip/506/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20152250.png"
  ],
  "507": [
    "/images/pictures/tours-vip/507/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20143454.png",
    "/images/pictures/tours-vip/507/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20143536.png",
    "/images/pictures/tours-vip/507/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20143606.png",
    "/images/pictures/tours-vip/507/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20143629.png",
    "/images/pictures/tours-vip/507/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20143653.png"
  ],
  "508": [
    "/images/pictures/tours-vip/508/groups-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20161737.png",
    "/images/pictures/tours-vip/508/groups-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20161809.png",
    "/images/pictures/tours-vip/508/groups-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20161834.png",
    "/images/pictures/tours-vip/508/groups-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20161900.png",
    "/images/pictures/tours-vip/508/groups-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20161921.png"
  ],
  "509": [
    "/images/pictures/tours-vip/509/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20161129.png",
    "/images/pictures/tours-vip/509/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20161230.png",
    "/images/pictures/tours-vip/509/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20161301.png",
    "/images/pictures/tours-vip/509/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20161324.png",
    "/images/pictures/tours-vip/509/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20161348.png"
  ],
  "510": [
    "/images/pictures/tours-vip/510/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160824.png",
    "/images/pictures/tours-vip/510/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160900.png",
    "/images/pictures/tours-vip/510/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160931.png",
    "/images/pictures/tours-vip/510/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160958.png",
    "/images/pictures/tours-vip/510/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20161025.png"
  ],
  "511": [
    "/images/pictures/tours-vip/511/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160519.png",
    "/images/pictures/tours-vip/511/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160606.png",
    "/images/pictures/tours-vip/511/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160633.png",
    "/images/pictures/tours-vip/511/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160659.png",
    "/images/pictures/tours-vip/511/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160729.png"
  ],
  "512": [
    "/images/pictures/tours-vip/512/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20143215.png",
    "/images/pictures/tours-vip/512/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20143252.png",
    "/images/pictures/tours-vip/512/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20143314.png",
    "/images/pictures/tours-vip/512/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20143336.png",
    "/images/pictures/tours-vip/512/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20143401.png"
  ],
  "513": [
    "/images/pictures/tours-vip/513/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160221.png",
    "/images/pictures/tours-vip/513/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160253.png",
    "/images/pictures/tours-vip/513/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160318.png",
    "/images/pictures/tours-vip/513/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160345.png",
    "/images/pictures/tours-vip/513/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160428.png"
  ],
  "515": [
    "/images/pictures/tours-vip/515/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20155926.png",
    "/images/pictures/tours-vip/515/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160005.png",
    "/images/pictures/tours-vip/515/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160044.png",
    "/images/pictures/tours-vip/515/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160114.png",
    "/images/pictures/tours-vip/515/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20160139.png"
  ],
  "516": [
    "/images/pictures/tours-vip/516/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20155658.png",
    "/images/pictures/tours-vip/516/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20155730.png",
    "/images/pictures/tours-vip/516/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20155754.png",
    "/images/pictures/tours-vip/516/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20155818.png",
    "/images/pictures/tours-vip/516/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20155841.png"
  ],
  "517": [
    "/images/pictures/tours-vip/517/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141130.png",
    "/images/pictures/tours-vip/517/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141212.png",
    "/images/pictures/tours-vip/517/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141234.png",
    "/images/pictures/tours-vip/517/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141258.png",
    "/images/pictures/tours-vip/517/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141326.png"
  ],
  "520": [
    "/images/pictures/tours-vip/520/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20140824.png",
    "/images/pictures/tours-vip/520/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20140902.png",
    "/images/pictures/tours-vip/520/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20140930.png",
    "/images/pictures/tours-vip/520/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20140956.png",
    "/images/pictures/tours-vip/520/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141020.png"
  ],
  "521": [
    "/images/pictures/tours-vip/521/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144318.png",
    "/images/pictures/tours-vip/521/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144359.png",
    "/images/pictures/tours-vip/521/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144421.png",
    "/images/pictures/tours-vip/521/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144449.png",
    "/images/pictures/tours-vip/521/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20144512.png"
  ],
  "522": [
    "/images/pictures/tours-vip/522/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20143740.png",
    "/images/pictures/tours-vip/522/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20143828.png",
    "/images/pictures/tours-vip/522/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20143848.png",
    "/images/pictures/tours-vip/522/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20143915.png",
    "/images/pictures/tours-vip/522/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20143939.png"
  ],
  "532": [
    "/images/pictures/tours-vip/532/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141711.png",
    "/images/pictures/tours-vip/532/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141801.png",
    "/images/pictures/tours-vip/532/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141829.png",
    "/images/pictures/tours-vip/532/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141850.png",
    "/images/pictures/tours-vip/532/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20141915.png"
  ],
  "533": [
    "/images/pictures/tours-vip/533/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145141.png",
    "/images/pictures/tours-vip/533/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145212.png",
    "/images/pictures/tours-vip/533/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145233.png",
    "/images/pictures/tours-vip/533/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145255.png",
    "/images/pictures/tours-vip/533/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20145315.png"
  ],
  "549": [
    "/images/pictures/tours-vip/549/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20151823.png",
    "/images/pictures/tours-vip/549/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20151909.png",
    "/images/pictures/tours-vip/549/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20151929.png",
    "/images/pictures/tours-vip/549/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20151953.png",
    "/images/pictures/tours-vip/549/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20152016.png"
  ],
  "550": [
    "/images/pictures/tours-vip/550/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20151523.png",
    "/images/pictures/tours-vip/550/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20151609.png",
    "/images/pictures/tours-vip/550/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20151632.png",
    "/images/pictures/tours-vip/550/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20151656.png",
    "/images/pictures/tours-vip/550/group-details/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202026-03-05%20151717.png"
  ]
}
