/**
 * Photo-Spots card — "The shots that'll end up on Instagram"
 *
 * Archetype + spot picking lives in
 * `src/lib/personalize/scorers/photo-spots.ts`. This renderer just maps
 * each spot key to its localized title/caption and a Lucide icon.
 */

import {
  Sunrise, Sunset, Mountain, Waves, Bird, Fish, Ship, Wind, Trees,
  Telescope, Camera, Sparkles,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { ModuleScore, ActivitySignals } from '@/lib/personalize/types'
import type {
  PhotoSpot,
  PhotoSpotIcon,
  PhotoSpotsProps,
} from '@/lib/personalize/scorers/photo-spots'

const ICON_MAP: Record<PhotoSpotIcon, LucideIcon> = {
  Sunrise,
  Sunset,
  Mountain,
  Waves,
  Bird,
  Fish,
  Ship,
  Wind,
  Trees,
  Telescope,
  Camera,
  Sparkles,
}

type Props = {
  signals: ActivitySignals
  score: ModuleScore
  locale: string
}

export function PhotoSpotsCard({ score: moduleScore, locale }: Props) {
  const props = moduleScore.props as PhotoSpotsProps
  const labels = TRANSLATIONS[locale] ?? TRANSLATIONS.fr

  return (
    <div className="rounded-3xl border border-neutral-200 bg-gradient-to-br from-violet-50/40 via-white to-rose-50/30 p-5">
      <div className="flex items-start gap-3">
        <div className="flex-shrink-0 rounded-2xl bg-gradient-to-br from-fuchsia-500 to-rose-500 p-2.5 shadow-sm">
          <Camera className="h-5 w-5 text-white" strokeWidth={2.25} />
        </div>
        <div className="min-w-0 flex-1">
          <h3 className="text-base font-semibold text-neutral-900">{labels.title}</h3>
          <p className="mt-0.5 text-sm text-neutral-600">{labels.subtitle}</p>
        </div>
      </div>

      <ul className="mt-4 grid gap-2 sm:grid-cols-2">
        {props.spots.map((spot, i) => (
          <SpotRow key={spot.key + i} spot={spot} labels={labels} index={i + 1} />
        ))}
      </ul>
    </div>
  )
}

function SpotRow({
  spot,
  labels,
  index,
}: {
  spot: PhotoSpot
  labels: Record<string, string>
  index: number
}) {
  const Icon = ICON_MAP[spot.icon] ?? Camera
  const title = labels[`spot_${spot.key}_title`] ?? spot.key
  const caption = labels[`spot_${spot.key}_caption`] ?? ''

  return (
    <li className="flex gap-3 rounded-xl border border-neutral-200/70 bg-white/80 p-3">
      <div className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-fuchsia-100 to-rose-100 text-fuchsia-700 ring-1 ring-fuchsia-200">
        <Icon className="h-4 w-4" strokeWidth={2.25} />
      </div>
      <div className="min-w-0 flex-1">
        <div className="flex items-baseline gap-1.5">
          <span className="text-[10px] font-bold text-fuchsia-600">{String(index).padStart(2, '0')}</span>
          <h4 className="text-sm font-semibold text-neutral-900">{title}</h4>
        </div>
        {caption && (
          <p className="mt-0.5 text-xs leading-snug text-neutral-600">{caption}</p>
        )}
      </div>
    </li>
  )
}

const TRANSLATIONS: Record<string, Record<string, string>> = {
  fr: {
    title: 'Les moments photo',
    subtitle: 'Les images que vous ramènerez de cette sortie.',

    // South boat / sunset
    spot_marinaDeparture_title: 'Départ du port',
    spot_marinaDeparture_caption: 'Lever de voiles, mât contre ciel, silhouettes de ponton.',
    spot_gomeraSilhouette_title: 'La Gomera en silhouette',
    spot_gomeraSilhouette_caption: 'La sœur volcanique émerge à l\'ouest — cadre idéal.',
    spot_sunsetDeck_title: 'Pont au crépuscule',
    spot_sunsetDeck_caption: 'Lumière dorée, coupe à la main, horizon sans fin.',
    spot_dolphinPod_title: 'Dauphins à l\'étrave',
    spot_dolphinPod_caption: 'Rafale photo quand ils surfent la vague du bateau.',
    spot_bowWaves_title: 'L\'étrave qui fend l\'eau',
    spot_bowWaves_caption: 'Slow-mo, spray d\'écume et soleil contre-jour.',

    // South paragliding
    spot_tauchoTakeoff_title: 'Décollage au Taucho',
    spot_tauchoTakeoff_caption: 'Course, voile qui se gonfle, moment d\'envol.',
    spot_aerialCoastline_title: 'Le littoral sud vu d\'en haut',
    spot_aerialCoastline_caption: 'Los Cristianos et Adeje comme maquette.',
    spot_canopySelfie_title: 'Selfie sous la voile',
    spot_canopySelfie_caption: 'Le classique grand-angle avec l\'île en arrière-plan.',

    // South beach
    spot_playaDelDuque_title: 'Playa del Duque',
    spot_playaDelDuque_caption: 'Sable doré, transats blancs, eau turquoise.',
    spot_palmWalkway_title: 'Allée de palmiers',
    spot_palmWalkway_caption: 'Alignement graphique vers le rivage.',
    spot_teideBackdrop_title: 'Le Teide en toile de fond',
    spot_teideBackdrop_caption: 'Le volcan qui surgit derrière les parasols.',

    // Centre volcano + sunset
    spot_canadasPlateau_title: 'Plateau des Cañadas',
    spot_canadasPlateau_caption: 'Caldeira lunaire, vue 360° sur la couronne.',
    spot_teideCone_title: 'Le cône du Teide',
    spot_teideCone_caption: 'La forme emblématique — cadrage vertical recommandé.',
    spot_sunsetRoques_title: 'Roques à l\'heure dorée',
    spot_sunsetRoques_caption: 'Ombres longues, rose désertique, silence.',
    spot_milkyWay_title: 'Voie lactée au-dessus',
    spot_milkyWay_caption: 'Pause longue, trépied léger, ciel parmi les plus purs d\'Europe.',
    spot_roquesDeGarcia_title: 'Roques de García',
    spot_roquesDeGarcia_caption: 'Les cheminées de pierre, repère culte du parc.',
    spot_minasDeSanJose_title: 'Minas de San José',
    spot_minasDeSanJose_caption: 'Dunes blanches de pierre ponce — effet Mars.',

    // West
    spot_gigantesCliffs_title: 'Falaises de Los Gigantes',
    spot_gigantesCliffs_caption: 'Basalte vertical sur 600 m — photo sur la mer.',
    spot_mascaBay_title: 'Baie de Masca',
    spot_mascaBay_caption: 'Eau turquoise au pied des falaises, cadre rare.',
    spot_turtleEncounter_title: 'Tortue en surface',
    spot_turtleEncounter_caption: 'Snorkelling rapide, top-shot verticale.',
    spot_cliffReflection_title: 'Falaises en reflet',
    spot_cliffReflection_caption: 'Mer calme, miroir parfait sur le basalte.',
    spot_mascaDescent_title: 'Descente du barranco',
    spot_mascaDescent_caption: 'Sentier serré, roche stratifiée, ombre et lumière.',
    spot_laurelForest_title: 'Forêt de lauriers',
    spot_laurelForest_caption: 'Mousse, brume, rayons filtrés — féerique.',
    spot_atlanticOverlook_title: 'Vue sur l\'Atlantique',
    spot_atlanticOverlook_caption: 'Depuis la côte nord-ouest, infini bleu.',

    // North
    spot_orotavaBalconies_title: 'Balcons de La Orotava',
    spot_orotavaBalconies_caption: 'Bois sculpté colonial, lumière du matin.',
    spot_anagaMist_title: 'Anaga dans la brume',
    spot_anagaMist_caption: 'Crêtes noyées, atmosphère jurassique.',
    spot_puertoCostal_title: 'Puerto de la Cruz — front de mer',
    spot_puertoCostal_caption: 'Basalte, pergolas et piscines naturelles.',
    spot_orcaShow_title: 'Show des orques',
    spot_orcaShow_caption: 'Éclaboussure au bon moment — cadrage horizontal.',
    spot_parrotColour_title: 'Perroquets multicolores',
    spot_parrotColour_caption: 'Macro sur plumage — flash interdit.',
    spot_gardenTrails_title: 'Allées tropicales',
    spot_gardenTrails_caption: 'Feuillages géants, eau vive, lumière filtrée.',

    // East
    spot_lagunaStreets_title: 'Rues de La Laguna',
    spot_lagunaStreets_caption: 'Façades pastel, pavés, patrimoine UNESCO.',
    spot_anagaHighland_title: 'Anaga en hauteur',
    spot_anagaHighland_caption: 'Panoramas à 360° sur les deux côtes.',
    spot_tenganaCoast_title: 'Côte de Taganana',
    spot_tenganaCoast_caption: 'Plages noires volcaniques, village perché.',

    // Ocean diving
    spot_blueWater_title: 'Plongée en bleu',
    spot_blueWater_caption: 'Lumière qui descend, silhouettes de palanquées.',
    spot_reefLife_title: 'Vie du récif',
    spot_reefLife_caption: 'Banc de poissons, textures, macro couleurs.',
    spot_surfaceCrew_title: 'Retour sur le bateau',
    spot_surfaceCrew_caption: 'Sourires, palmes qui s\'envolent, adrénaline.',

    // Generic adrenaline
    spot_actionShot_title: 'Action pure',
    spot_actionShot_caption: 'Burst photo, vitesse, expression.',
    spot_gearCloseup_title: 'Le matos en gros plan',
    spot_gearCloseup_caption: 'Textures techniques, ambiance pro.',
    spot_afterGlow_title: 'Après l\'effort',
    spot_afterGlow_caption: 'Regards, lumière dorée, respiration.',

    // Generic nature
    spot_landscape_title: 'Le paysage',
    spot_landscape_caption: 'Plan large, couches de relief, horizon.',
    spot_trailDetail_title: 'Le sentier en détail',
    spot_trailDetail_caption: 'Texture du sol, ombre, petits éléments.',
    spot_summitSelfie_title: 'Selfie au sommet',
    spot_summitSelfie_caption: 'La récompense du chemin — panorama derrière.',
  },
  en: {
    title: 'Photo moments',
    subtitle: 'The shots you\'ll bring back from this outing.',
    spot_marinaDeparture_title: 'Marina departure',
    spot_marinaDeparture_caption: 'Raising sails, mast against the sky, pontoon silhouettes.',
    spot_gomeraSilhouette_title: 'La Gomera silhouette',
    spot_gomeraSilhouette_caption: 'The volcanic sister rises to the west — perfect framing.',
    spot_sunsetDeck_title: 'Deck at dusk',
    spot_sunsetDeck_caption: 'Golden light, glass in hand, endless horizon.',
    spot_dolphinPod_title: 'Dolphins at the bow',
    spot_dolphinPod_caption: 'Rapid-fire shots as they surf the boat\'s wake.',
    spot_bowWaves_title: 'The bow cutting water',
    spot_bowWaves_caption: 'Slow-mo, spray and backlit sun.',
    spot_tauchoTakeoff_title: 'Taucho takeoff',
    spot_tauchoTakeoff_caption: 'Run, sail inflates, moment of lift.',
    spot_aerialCoastline_title: 'South coast from above',
    spot_aerialCoastline_caption: 'Los Cristianos and Adeje like a miniature.',
    spot_canopySelfie_title: 'Selfie under the canopy',
    spot_canopySelfie_caption: 'The classic wide-angle with the island below.',
    spot_playaDelDuque_title: 'Playa del Duque',
    spot_playaDelDuque_caption: 'Golden sand, white loungers, turquoise water.',
    spot_palmWalkway_title: 'Palm walkway',
    spot_palmWalkway_caption: 'Graphic alignment toward the shore.',
    spot_teideBackdrop_title: 'Teide as backdrop',
    spot_teideBackdrop_caption: 'The volcano rising behind the parasols.',
    spot_canadasPlateau_title: 'Las Cañadas plateau',
    spot_canadasPlateau_caption: 'Lunar caldera, 360° view of the crown.',
    spot_teideCone_title: 'The Teide cone',
    spot_teideCone_caption: 'The iconic shape — try vertical framing.',
    spot_sunsetRoques_title: 'Roques at golden hour',
    spot_sunsetRoques_caption: 'Long shadows, desert pink, silence.',
    spot_milkyWay_title: 'Milky Way overhead',
    spot_milkyWay_caption: 'Long exposure, light tripod — Europe\'s clearest skies.',
    spot_roquesDeGarcia_title: 'Roques de García',
    spot_roquesDeGarcia_caption: 'Stone chimneys — the park\'s cult landmark.',
    spot_minasDeSanJose_title: 'Minas de San José',
    spot_minasDeSanJose_caption: 'White pumice dunes — Mars-like effect.',
    spot_gigantesCliffs_title: 'Los Gigantes cliffs',
    spot_gigantesCliffs_caption: 'Vertical basalt rising 600 m over the sea.',
    spot_mascaBay_title: 'Masca bay',
    spot_mascaBay_caption: 'Turquoise water at the foot of the cliffs.',
    spot_turtleEncounter_title: 'Turtle at surface',
    spot_turtleEncounter_caption: 'Fast snorkel — vertical top-shot.',
    spot_cliffReflection_title: 'Cliffs reflected',
    spot_cliffReflection_caption: 'Still sea, perfect basalt mirror.',
    spot_mascaDescent_title: 'Barranco descent',
    spot_mascaDescent_caption: 'Narrow trail, layered rock, light and shadow.',
    spot_laurelForest_title: 'Laurel forest',
    spot_laurelForest_caption: 'Moss, mist, filtered beams — fairy-tale.',
    spot_atlanticOverlook_title: 'Atlantic overlook',
    spot_atlanticOverlook_caption: 'From the north-west coast, endless blue.',
    spot_orotavaBalconies_title: 'La Orotava balconies',
    spot_orotavaBalconies_caption: 'Colonial carved wood, morning light.',
    spot_anagaMist_title: 'Anaga in mist',
    spot_anagaMist_caption: 'Drowned ridges, jurassic feel.',
    spot_puertoCostal_title: 'Puerto de la Cruz seafront',
    spot_puertoCostal_caption: 'Basalt, pergolas, natural pools.',
    spot_orcaShow_title: 'Orca show',
    spot_orcaShow_caption: 'Time the splash — horizontal framing.',
    spot_parrotColour_title: 'Colourful parrots',
    spot_parrotColour_caption: 'Plumage macro — no flash.',
    spot_gardenTrails_title: 'Tropical trails',
    spot_gardenTrails_caption: 'Giant foliage, running water, filtered light.',
    spot_lagunaStreets_title: 'La Laguna streets',
    spot_lagunaStreets_caption: 'Pastel façades, cobblestones, UNESCO heritage.',
    spot_anagaHighland_title: 'Anaga highlands',
    spot_anagaHighland_caption: '360° panoramas over both coasts.',
    spot_tenganaCoast_title: 'Taganana coast',
    spot_tenganaCoast_caption: 'Black volcanic beaches, village clinging above.',
    spot_blueWater_title: 'Blue-water dive',
    spot_blueWater_caption: 'Light descending, dive-team silhouettes.',
    spot_reefLife_title: 'Reef life',
    spot_reefLife_caption: 'Fish school, textures, macro colours.',
    spot_surfaceCrew_title: 'Back on the boat',
    spot_surfaceCrew_caption: 'Smiles, flying fins, adrenaline.',
    spot_actionShot_title: 'Pure action',
    spot_actionShot_caption: 'Burst, speed, expression.',
    spot_gearCloseup_title: 'Gear close-up',
    spot_gearCloseup_caption: 'Technical textures, pro vibe.',
    spot_afterGlow_title: 'After the effort',
    spot_afterGlow_caption: 'Eyes, golden light, breath.',
    spot_landscape_title: 'The landscape',
    spot_landscape_caption: 'Wide shot, layered relief, horizon.',
    spot_trailDetail_title: 'Trail detail',
    spot_trailDetail_caption: 'Ground texture, shadow, small elements.',
    spot_summitSelfie_title: 'Summit selfie',
    spot_summitSelfie_caption: 'The reward of the climb — panorama behind.',
  },
  es: {
    title: 'Momentos foto',
    subtitle: 'Las imágenes que te traerás de esta salida.',
    spot_marinaDeparture_title: 'Salida del puerto',
    spot_marinaDeparture_caption: 'Izado de velas, mástil contra el cielo, siluetas de pontón.',
    spot_gomeraSilhouette_title: 'La Gomera en silueta',
    spot_gomeraSilhouette_caption: 'La hermana volcánica emerge al oeste.',
    spot_sunsetDeck_title: 'Cubierta al atardecer',
    spot_sunsetDeck_caption: 'Luz dorada, copa en mano, horizonte infinito.',
    spot_dolphinPod_title: 'Delfines en la proa',
    spot_dolphinPod_caption: 'Ráfaga de fotos cuando surfean la ola.',
    spot_bowWaves_title: 'Proa cortando el agua',
    spot_bowWaves_caption: 'Cámara lenta, espuma, contraluz.',
    spot_tauchoTakeoff_title: 'Despegue en Taucho',
    spot_tauchoTakeoff_caption: 'Carrera, vela que se hincha, elevación.',
    spot_aerialCoastline_title: 'La costa sur desde arriba',
    spot_aerialCoastline_caption: 'Los Cristianos y Adeje como maqueta.',
    spot_canopySelfie_title: 'Selfie bajo la vela',
    spot_canopySelfie_caption: 'El clásico gran angular con la isla abajo.',
    spot_playaDelDuque_title: 'Playa del Duque',
    spot_playaDelDuque_caption: 'Arena dorada, hamacas blancas, agua turquesa.',
    spot_palmWalkway_title: 'Paseo de palmeras',
    spot_palmWalkway_caption: 'Alineación gráfica hacia el mar.',
    spot_teideBackdrop_title: 'El Teide de fondo',
    spot_teideBackdrop_caption: 'El volcán surgiendo detrás de las sombrillas.',
    spot_canadasPlateau_title: 'Meseta de Las Cañadas',
    spot_canadasPlateau_caption: 'Caldera lunar, vista 360° de la corona.',
    spot_teideCone_title: 'El cono del Teide',
    spot_teideCone_caption: 'La forma icónica — prueba en vertical.',
    spot_sunsetRoques_title: 'Roques a la hora dorada',
    spot_sunsetRoques_caption: 'Sombras largas, rosa desértico, silencio.',
    spot_milkyWay_title: 'Vía Láctea arriba',
    spot_milkyWay_caption: 'Exposición larga — cielos de los más puros de Europa.',
    spot_roquesDeGarcia_title: 'Roques de García',
    spot_roquesDeGarcia_caption: 'Chimeneas de piedra, emblema del parque.',
    spot_minasDeSanJose_title: 'Minas de San José',
    spot_minasDeSanJose_caption: 'Dunas blancas de piedra pómez — efecto Marte.',
    spot_gigantesCliffs_title: 'Acantilados de Los Gigantes',
    spot_gigantesCliffs_caption: 'Basalto vertical de 600 m sobre el mar.',
    spot_mascaBay_title: 'Bahía de Masca',
    spot_mascaBay_caption: 'Agua turquesa al pie de los acantilados.',
    spot_turtleEncounter_title: 'Tortuga en superficie',
    spot_turtleEncounter_caption: 'Snorkel rápido — toma vertical.',
    spot_cliffReflection_title: 'Acantilados reflejados',
    spot_cliffReflection_caption: 'Mar en calma, espejo perfecto.',
    spot_mascaDescent_title: 'Bajada del barranco',
    spot_mascaDescent_caption: 'Sendero estrecho, roca estratificada, luz y sombra.',
    spot_laurelForest_title: 'Bosque de laurisilva',
    spot_laurelForest_caption: 'Musgo, bruma, rayos filtrados — de cuento.',
    spot_atlanticOverlook_title: 'Vista al Atlántico',
    spot_atlanticOverlook_caption: 'Desde la costa noroeste, azul infinito.',
    spot_orotavaBalconies_title: 'Balcones de La Orotava',
    spot_orotavaBalconies_caption: 'Madera colonial tallada, luz matutina.',
    spot_anagaMist_title: 'Anaga entre nieblas',
    spot_anagaMist_caption: 'Crestas sumergidas, ambiente jurásico.',
    spot_puertoCostal_title: 'Puerto de la Cruz — paseo marítimo',
    spot_puertoCostal_caption: 'Basalto, pérgolas y piscinas naturales.',
    spot_orcaShow_title: 'Show de orcas',
    spot_orcaShow_caption: 'Salpicadura en el momento — toma horizontal.',
    spot_parrotColour_title: 'Loros multicolores',
    spot_parrotColour_caption: 'Macro de plumaje — sin flash.',
    spot_gardenTrails_title: 'Senderos tropicales',
    spot_gardenTrails_caption: 'Follaje gigante, agua corriente, luz filtrada.',
    spot_lagunaStreets_title: 'Calles de La Laguna',
    spot_lagunaStreets_caption: 'Fachadas pastel, adoquines, patrimonio UNESCO.',
    spot_anagaHighland_title: 'Anaga en altura',
    spot_anagaHighland_caption: 'Panoramas 360° sobre ambas costas.',
    spot_tenganaCoast_title: 'Costa de Taganana',
    spot_tenganaCoast_caption: 'Playas negras volcánicas, pueblo en alto.',
    spot_blueWater_title: 'Inmersión en azul',
    spot_blueWater_caption: 'Luz descendente, siluetas del equipo.',
    spot_reefLife_title: 'Vida del arrecife',
    spot_reefLife_caption: 'Banco de peces, texturas, macro de colores.',
    spot_surfaceCrew_title: 'Vuelta al barco',
    spot_surfaceCrew_caption: 'Sonrisas, aletas voladoras, adrenalina.',
    spot_actionShot_title: 'Acción pura',
    spot_actionShot_caption: 'Ráfaga, velocidad, expresión.',
    spot_gearCloseup_title: 'Equipo en primer plano',
    spot_gearCloseup_caption: 'Texturas técnicas, vibe pro.',
    spot_afterGlow_title: 'Tras el esfuerzo',
    spot_afterGlow_caption: 'Miradas, luz dorada, respiración.',
    spot_landscape_title: 'El paisaje',
    spot_landscape_caption: 'Plano amplio, capas de relieve, horizonte.',
    spot_trailDetail_title: 'Sendero en detalle',
    spot_trailDetail_caption: 'Textura del suelo, sombra, pequeños elementos.',
    spot_summitSelfie_title: 'Selfie en la cumbre',
    spot_summitSelfie_caption: 'La recompensa — panorama atrás.',
  },
  de: {
    title: 'Foto-Momente',
    subtitle: 'Die Aufnahmen, die Sie mitbringen werden.',
    spot_marinaDeparture_title: 'Abfahrt vom Hafen',
    spot_marinaDeparture_caption: 'Segel setzen, Mast vor Himmel, Stegsilhouetten.',
    spot_gomeraSilhouette_title: 'La Gomera als Silhouette',
    spot_gomeraSilhouette_caption: 'Die Vulkanschwester erscheint im Westen.',
    spot_sunsetDeck_title: 'Deck in der Dämmerung',
    spot_sunsetDeck_caption: 'Goldenes Licht, Glas in der Hand, endloser Horizont.',
    spot_dolphinPod_title: 'Delfine am Bug',
    spot_dolphinPod_caption: 'Serienbild, wenn sie die Bugwelle reiten.',
    spot_bowWaves_title: 'Der Bug schneidet das Wasser',
    spot_bowWaves_caption: 'Zeitlupe, Gischt, Gegenlicht.',
    spot_tauchoTakeoff_title: 'Start am Taucho',
    spot_tauchoTakeoff_caption: 'Anlauf, Segel füllt sich, Abheben.',
    spot_aerialCoastline_title: 'Südküste von oben',
    spot_aerialCoastline_caption: 'Los Cristianos und Adeje wie ein Modell.',
    spot_canopySelfie_title: 'Selfie unter dem Schirm',
    spot_canopySelfie_caption: 'Der Klassiker mit der Insel darunter.',
    spot_playaDelDuque_title: 'Playa del Duque',
    spot_playaDelDuque_caption: 'Goldener Sand, weiße Liegen, türkises Wasser.',
    spot_palmWalkway_title: 'Palmenallee',
    spot_palmWalkway_caption: 'Grafische Linie zum Strand.',
    spot_teideBackdrop_title: 'Teide im Hintergrund',
    spot_teideBackdrop_caption: 'Der Vulkan hinter den Schirmen.',
    spot_canadasPlateau_title: 'Las-Cañadas-Hochebene',
    spot_canadasPlateau_caption: 'Mondkrater, 360°-Blick auf die Krone.',
    spot_teideCone_title: 'Der Teide-Kegel',
    spot_teideCone_caption: 'Die ikonische Form — hochkant versuchen.',
    spot_sunsetRoques_title: 'Roques zur goldenen Stunde',
    spot_sunsetRoques_caption: 'Lange Schatten, Wüstenrosa, Stille.',
    spot_milkyWay_title: 'Milchstraße oben',
    spot_milkyWay_caption: 'Lange Belichtung — Europas klarster Himmel.',
    spot_roquesDeGarcia_title: 'Roques de García',
    spot_roquesDeGarcia_caption: 'Steinkamine — Wahrzeichen des Parks.',
    spot_minasDeSanJose_title: 'Minas de San José',
    spot_minasDeSanJose_caption: 'Weiße Bimsdünen — Mars-Effekt.',
    spot_gigantesCliffs_title: 'Klippen von Los Gigantes',
    spot_gigantesCliffs_caption: '600 m senkrechter Basalt über dem Meer.',
    spot_mascaBay_title: 'Bucht von Masca',
    spot_mascaBay_caption: 'Türkises Wasser am Fuß der Klippen.',
    spot_turtleEncounter_title: 'Schildkröte an der Oberfläche',
    spot_turtleEncounter_caption: 'Schneller Schnorchelmoment.',
    spot_cliffReflection_title: 'Klippen gespiegelt',
    spot_cliffReflection_caption: 'Ruhige See, perfekter Spiegel.',
    spot_mascaDescent_title: 'Abstieg in den Barranco',
    spot_mascaDescent_caption: 'Schmaler Pfad, geschichteter Fels.',
    spot_laurelForest_title: 'Lorbeerwald',
    spot_laurelForest_caption: 'Moos, Nebel, gefilterte Strahlen.',
    spot_atlanticOverlook_title: 'Blick auf den Atlantik',
    spot_atlanticOverlook_caption: 'Von der Nordwestküste, endloses Blau.',
    spot_orotavaBalconies_title: 'Balkone von La Orotava',
    spot_orotavaBalconies_caption: 'Geschnitztes Kolonialholz, Morgenlicht.',
    spot_anagaMist_title: 'Anaga im Nebel',
    spot_anagaMist_caption: 'Versunkene Kämme, jurassische Stimmung.',
    spot_puertoCostal_title: 'Puerto de la Cruz — Strandpromenade',
    spot_puertoCostal_caption: 'Basalt, Pergolen, Naturpools.',
    spot_orcaShow_title: 'Orca-Show',
    spot_orcaShow_caption: 'Spritzer im richtigen Moment.',
    spot_parrotColour_title: 'Bunte Papageien',
    spot_parrotColour_caption: 'Gefieder-Makro — kein Blitz.',
    spot_gardenTrails_title: 'Tropische Pfade',
    spot_gardenTrails_caption: 'Riesenblätter, fließendes Wasser, gefiltertes Licht.',
    spot_lagunaStreets_title: 'Gassen von La Laguna',
    spot_lagunaStreets_caption: 'Pastellfassaden, Kopfstein, UNESCO-Erbe.',
    spot_anagaHighland_title: 'Anaga-Hochland',
    spot_anagaHighland_caption: '360°-Panoramen beider Küsten.',
    spot_tenganaCoast_title: 'Taganana-Küste',
    spot_tenganaCoast_caption: 'Schwarze Vulkanstrände, Dorf darüber.',
    spot_blueWater_title: 'Blauwasser-Tauchgang',
    spot_blueWater_caption: 'Abfallendes Licht, Taucher-Silhouetten.',
    spot_reefLife_title: 'Riffleben',
    spot_reefLife_caption: 'Fischschwarm, Texturen, Makro-Farben.',
    spot_surfaceCrew_title: 'Zurück auf dem Boot',
    spot_surfaceCrew_caption: 'Lächeln, fliegende Flossen, Adrenalin.',
    spot_actionShot_title: 'Pure Action',
    spot_actionShot_caption: 'Serie, Geschwindigkeit, Ausdruck.',
    spot_gearCloseup_title: 'Ausrüstung im Detail',
    spot_gearCloseup_caption: 'Technische Texturen, Profi-Feeling.',
    spot_afterGlow_title: 'Nach der Anstrengung',
    spot_afterGlow_caption: 'Blicke, goldenes Licht, Atem.',
    spot_landscape_title: 'Die Landschaft',
    spot_landscape_caption: 'Weite, geschichtetes Relief, Horizont.',
    spot_trailDetail_title: 'Wegdetail',
    spot_trailDetail_caption: 'Bodentextur, Schatten, kleine Elemente.',
    spot_summitSelfie_title: 'Gipfel-Selfie',
    spot_summitSelfie_caption: 'Die Belohnung — Panorama dahinter.',
  },
  it: {
    title: 'Momenti foto',
    subtitle: 'Le immagini che porterai a casa.',
    spot_marinaDeparture_title: 'Partenza dal porto',
    spot_marinaDeparture_caption: 'Vele issate, albero contro cielo, sagome del molo.',
    spot_gomeraSilhouette_title: 'La Gomera in silhouette',
    spot_gomeraSilhouette_caption: 'La sorella vulcanica emerge a ovest.',
    spot_sunsetDeck_title: 'Ponte al tramonto',
    spot_sunsetDeck_caption: 'Luce dorata, bicchiere in mano, orizzonte infinito.',
    spot_dolphinPod_title: 'Delfini alla prua',
    spot_dolphinPod_caption: 'Raffica di foto mentre cavalcano l\'onda.',
    spot_bowWaves_title: 'Prua che fende l\'acqua',
    spot_bowWaves_caption: 'Slow-mo, spruzzi, controluce.',
    spot_tauchoTakeoff_title: 'Decollo al Taucho',
    spot_tauchoTakeoff_caption: 'Corsa, vela che si gonfia, stacco.',
    spot_aerialCoastline_title: 'Costa sud dall\'alto',
    spot_aerialCoastline_caption: 'Los Cristianos e Adeje come un plastico.',
    spot_canopySelfie_title: 'Selfie sotto la vela',
    spot_canopySelfie_caption: 'Il classico grandangolo con l\'isola sotto.',
    spot_playaDelDuque_title: 'Playa del Duque',
    spot_playaDelDuque_caption: 'Sabbia dorata, lettini bianchi, acqua turchese.',
    spot_palmWalkway_title: 'Viale delle palme',
    spot_palmWalkway_caption: 'Allineamento grafico verso la riva.',
    spot_teideBackdrop_title: 'Il Teide sullo sfondo',
    spot_teideBackdrop_caption: 'Il vulcano dietro gli ombrelloni.',
    spot_canadasPlateau_title: 'Altopiano di Las Cañadas',
    spot_canadasPlateau_caption: 'Caldera lunare, vista 360°.',
    spot_teideCone_title: 'Il cono del Teide',
    spot_teideCone_caption: 'La forma iconica — prova in verticale.',
    spot_sunsetRoques_title: 'Roques all\'ora dorata',
    spot_sunsetRoques_caption: 'Ombre lunghe, rosa desertico, silenzio.',
    spot_milkyWay_title: 'Via Lattea sopra',
    spot_milkyWay_caption: 'Posa lunga — cieli tra i più puri d\'Europa.',
    spot_roquesDeGarcia_title: 'Roques de García',
    spot_roquesDeGarcia_caption: 'Camini di pietra — simbolo del parco.',
    spot_minasDeSanJose_title: 'Minas de San José',
    spot_minasDeSanJose_caption: 'Dune bianche di pomice — effetto Marte.',
    spot_gigantesCliffs_title: 'Scogliere di Los Gigantes',
    spot_gigantesCliffs_caption: 'Basalto verticale 600 m sul mare.',
    spot_mascaBay_title: 'Baia di Masca',
    spot_mascaBay_caption: 'Acqua turchese ai piedi delle scogliere.',
    spot_turtleEncounter_title: 'Tartaruga in superficie',
    spot_turtleEncounter_caption: 'Snorkel rapido — scatto verticale.',
    spot_cliffReflection_title: 'Scogliere riflesse',
    spot_cliffReflection_caption: 'Mare calmo, specchio perfetto.',
    spot_mascaDescent_title: 'Discesa del barranco',
    spot_mascaDescent_caption: 'Sentiero stretto, roccia stratificata.',
    spot_laurelForest_title: 'Foresta di alloro',
    spot_laurelForest_caption: 'Muschio, bruma, raggi filtrati.',
    spot_atlanticOverlook_title: 'Vista sull\'Atlantico',
    spot_atlanticOverlook_caption: 'Dalla costa nord-ovest, blu infinito.',
    spot_orotavaBalconies_title: 'Balconi di La Orotava',
    spot_orotavaBalconies_caption: 'Legno coloniale intagliato, luce del mattino.',
    spot_anagaMist_title: 'Anaga nella bruma',
    spot_anagaMist_caption: 'Creste sommerse, atmosfera giurassica.',
    spot_puertoCostal_title: 'Puerto de la Cruz — lungomare',
    spot_puertoCostal_caption: 'Basalto, pergole, piscine naturali.',
    spot_orcaShow_title: 'Show delle orche',
    spot_orcaShow_caption: 'Schizzo al momento giusto.',
    spot_parrotColour_title: 'Pappagalli colorati',
    spot_parrotColour_caption: 'Macro di piumaggio — niente flash.',
    spot_gardenTrails_title: 'Sentieri tropicali',
    spot_gardenTrails_caption: 'Fogliame gigante, acqua, luce filtrata.',
    spot_lagunaStreets_title: 'Vie di La Laguna',
    spot_lagunaStreets_caption: 'Facciate pastello, selciato, UNESCO.',
    spot_anagaHighland_title: 'Anaga in quota',
    spot_anagaHighland_caption: 'Panoramiche 360° su entrambe le coste.',
    spot_tenganaCoast_title: 'Costa di Taganana',
    spot_tenganaCoast_caption: 'Spiagge nere vulcaniche, borgo in alto.',
    spot_blueWater_title: 'Immersione in blu',
    spot_blueWater_caption: 'Luce che scende, silhouette del team.',
    spot_reefLife_title: 'Vita della barriera',
    spot_reefLife_caption: 'Banco di pesci, texture, macro.',
    spot_surfaceCrew_title: 'Rientro in barca',
    spot_surfaceCrew_caption: 'Sorrisi, pinne volanti, adrenalina.',
    spot_actionShot_title: 'Azione pura',
    spot_actionShot_caption: 'Raffica, velocità, espressione.',
    spot_gearCloseup_title: 'Attrezzatura in primo piano',
    spot_gearCloseup_caption: 'Texture tecniche, vibe pro.',
    spot_afterGlow_title: 'Dopo lo sforzo',
    spot_afterGlow_caption: 'Sguardi, luce dorata, respiro.',
    spot_landscape_title: 'Il paesaggio',
    spot_landscape_caption: 'Piano largo, strati, orizzonte.',
    spot_trailDetail_title: 'Dettaglio del sentiero',
    spot_trailDetail_caption: 'Texture, ombra, piccoli elementi.',
    spot_summitSelfie_title: 'Selfie in vetta',
    spot_summitSelfie_caption: 'La ricompensa — panorama alle spalle.',
  },
  ru: {
    title: 'Фото-моменты',
    subtitle: 'Кадры, которые вы привезёте с этой поездки.',
    spot_marinaDeparture_title: 'Выход из порта',
    spot_marinaDeparture_caption: 'Подъём парусов, мачта на фоне неба, силуэты пирса.',
    spot_gomeraSilhouette_title: 'Ла-Гомера силуэтом',
    spot_gomeraSilhouette_caption: 'Вулканическая сестра на западе.',
    spot_sunsetDeck_title: 'Палуба на закате',
    spot_sunsetDeck_caption: 'Золотой свет, бокал в руке, бесконечный горизонт.',
    spot_dolphinPod_title: 'Дельфины у форштевня',
    spot_dolphinPod_caption: 'Серия кадров, когда они серфят волну.',
    spot_bowWaves_title: 'Нос, режущий воду',
    spot_bowWaves_caption: 'Slow-mo, брызги, контровой свет.',
    spot_tauchoTakeoff_title: 'Старт с Тауко',
    spot_tauchoTakeoff_caption: 'Разбег, парус наполняется, отрыв.',
    spot_aerialCoastline_title: 'Южный берег сверху',
    spot_aerialCoastline_caption: 'Los Cristianos и Adeje как макет.',
    spot_canopySelfie_title: 'Селфи под парашютом',
    spot_canopySelfie_caption: 'Классика — широкий угол с островом внизу.',
    spot_playaDelDuque_title: 'Playa del Duque',
    spot_playaDelDuque_caption: 'Золотой песок, белые шезлонги, бирюза.',
    spot_palmWalkway_title: 'Пальмовая аллея',
    spot_palmWalkway_caption: 'Графичная линия к берегу.',
    spot_teideBackdrop_title: 'Тейде на заднем плане',
    spot_teideBackdrop_caption: 'Вулкан поднимается за зонтиками.',
    spot_canadasPlateau_title: 'Плато Las Cañadas',
    spot_canadasPlateau_caption: 'Лунный кратер, обзор 360°.',
    spot_teideCone_title: 'Конус Тейде',
    spot_teideCone_caption: 'Иконическая форма — попробуйте вертикаль.',
    spot_sunsetRoques_title: 'Roques на золотом часе',
    spot_sunsetRoques_caption: 'Длинные тени, пустынно-розовый, тишина.',
    spot_milkyWay_title: 'Млечный Путь',
    spot_milkyWay_caption: 'Длинная выдержка — одно из чистейших неб Европы.',
    spot_roquesDeGarcia_title: 'Roques de García',
    spot_roquesDeGarcia_caption: 'Каменные трубы — символ парка.',
    spot_minasDeSanJose_title: 'Minas de San José',
    spot_minasDeSanJose_caption: 'Белые пемзовые дюны — эффект Марса.',
    spot_gigantesCliffs_title: 'Скалы Лос-Хигантес',
    spot_gigantesCliffs_caption: '600 м вертикального базальта над морем.',
    spot_mascaBay_title: 'Бухта Маска',
    spot_mascaBay_caption: 'Бирюзовая вода у основания скал.',
    spot_turtleEncounter_title: 'Черепаха на поверхности',
    spot_turtleEncounter_caption: 'Быстрый снорклинг — вертикальный кадр.',
    spot_cliffReflection_title: 'Скалы в отражении',
    spot_cliffReflection_caption: 'Штиль, идеальное зеркало.',
    spot_mascaDescent_title: 'Спуск в барранко',
    spot_mascaDescent_caption: 'Узкая тропа, слоистая порода.',
    spot_laurelForest_title: 'Лавровый лес',
    spot_laurelForest_caption: 'Мох, туман, фильтрованные лучи.',
    spot_atlanticOverlook_title: 'Вид на Атлантику',
    spot_atlanticOverlook_caption: 'С северо-западного побережья, бесконечный синий.',
    spot_orotavaBalconies_title: 'Балконы Ла-Оротавы',
    spot_orotavaBalconies_caption: 'Резная колониальная древесина.',
    spot_anagaMist_title: 'Анага в тумане',
    spot_anagaMist_caption: 'Затонувшие гребни, юрская атмосфера.',
    spot_puertoCostal_title: 'Пуэрто-де-ла-Крус — набережная',
    spot_puertoCostal_caption: 'Базальт, перголы, природные бассейны.',
    spot_orcaShow_title: 'Шоу касаток',
    spot_orcaShow_caption: 'Поймай брызги в нужный момент.',
    spot_parrotColour_title: 'Разноцветные попугаи',
    spot_parrotColour_caption: 'Макро оперения — без вспышки.',
    spot_gardenTrails_title: 'Тропические аллеи',
    spot_gardenTrails_caption: 'Гигантская листва, проточная вода.',
    spot_lagunaStreets_title: 'Улочки Ла-Лагуны',
    spot_lagunaStreets_caption: 'Пастельные фасады, брусчатка, ЮНЕСКО.',
    spot_anagaHighland_title: 'Анага в высоте',
    spot_anagaHighland_caption: 'Панорамы 360° обоих берегов.',
    spot_tenganaCoast_title: 'Побережье Таганана',
    spot_tenganaCoast_caption: 'Чёрные вулканические пляжи, деревня наверху.',
    spot_blueWater_title: 'Погружение в синеву',
    spot_blueWater_caption: 'Свет уходит вниз, силуэты команды.',
    spot_reefLife_title: 'Жизнь рифа',
    spot_reefLife_caption: 'Стая рыб, текстуры, макро.',
    spot_surfaceCrew_title: 'Возвращение на лодку',
    spot_surfaceCrew_caption: 'Улыбки, летящие ласты, адреналин.',
    spot_actionShot_title: 'Чистое движение',
    spot_actionShot_caption: 'Серия, скорость, выражение.',
    spot_gearCloseup_title: 'Снаряжение крупным планом',
    spot_gearCloseup_caption: 'Технические текстуры, pro-ощущение.',
    spot_afterGlow_title: 'После усилия',
    spot_afterGlow_caption: 'Взгляды, золотой свет, дыхание.',
    spot_landscape_title: 'Пейзаж',
    spot_landscape_caption: 'Общий план, слои рельефа, горизонт.',
    spot_trailDetail_title: 'Детали тропы',
    spot_trailDetail_caption: 'Текстура земли, тень, мелочи.',
    spot_summitSelfie_title: 'Селфи на вершине',
    spot_summitSelfie_caption: 'Награда — панорама позади.',
  },
}
